/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-22 04:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layouts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/admin/git/campingEverywhere_group4/camping/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687409442053L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("input:autofill, input:autofill:hover, input:autofill:focus, input:autofill:active\r\n");
      out.write("	{\r\n");
      out.write("	-webkit-text-fill-color: #000;\r\n");
      out.write("	-webkit-box-shadow: 0 0 0px 1000px #fff inset;\r\n");
      out.write("	box-shadow: 0 0 0px 1000px transparent inset;\r\n");
      out.write("	transition: background-color 5000s ease-in-out 0s;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- ======= Header Top======= -->\r\n");
      out.write("	<header id=\"header_top\" class=\"d-flex align-items-center\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container d-flex align-items-center justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"logo\">\r\n");
      out.write("				<a href=\"main.do\"><img src=\"assets/img/favicon.png\" alt=\"로고\"></a>\r\n");
      out.write("				<form id=\"frmsearch\" action=\"productSearch.do\" method=\"post\">\r\n");
      out.write("					<input type=\"text\" placeholder=\"검색\" id=\"search\" name=\"search\">\r\n");
      out.write("					<button type=\"submit\">\r\n");
      out.write("						<i class=\"fa-solid fa-magnifying-glass\" style=\"color: #9c9c9c;\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<li><a class=\"small nav-link scrollto\"\r\n");
      out.write("						href=\"javascript:cart()\">장바구니</a></li>\r\n");
      out.write("					<li><a class=\"small nav-link scrollto\" href=\"javascript:myPage()\">마이페이지</a></li>\r\n");
      out.write("					<li><a class=\"small nav-link scrollto\"\r\n");
      out.write("						href=\"javascript:delivery()\">주문/배송조회</a></li>\r\n");
      out.write("					<li><a class=\"small nav-link scrollto\" href=\"boardList.do\">고객센터</a></li>\r\n");
      out.write("					<li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"wrap\">\r\n");
      out.write("							<div class=\"darkmode\">\r\n");
      out.write("								<div class=\"inner\">\r\n");
      out.write("									<input type=\"radio\" name=\"toggle\" id=\"toggle-radio-light\"\r\n");
      out.write("										checked><label for=\"toggle-radio-light\"\r\n");
      out.write("										class=\"tolight\"><i class=\"fas fa-sun tolight\"></i></label> <input\r\n");
      out.write("										type=\"radio\" name=\"toggle\" id=\"toggle-radio-dark\"><label\r\n");
      out.write("										for=\"toggle-radio-dark\" class=\"todark\"><i\r\n");
      out.write("										class=\"fas fa-moon todark\"></i></label>\r\n");
      out.write("									<div class=\"darkmode-bg\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<i class=\"bi bi-list mobile-nav-toggle\"></i>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<!-- hero -->\r\n");
      out.write("	<section id=\"hero\"\r\n");
      out.write("		class=\"d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("		<h1>Camping Everywhere</h1>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- ======= Header Bottom======= -->\r\n");
      out.write("	<header id=\"header\" class=\"d-flex align-items-center\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"container d-flex align-items-center justify-content-center\">\r\n");
      out.write("			<nav id=\"navbar\" class=\"navbar\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a class=\"nav-link scrollto\" href=\"productList.do?value=전체상품\">전체상품</a></li>\r\n");
      out.write("					<li><a class=\"nav-link scrollto\"\r\n");
      out.write("						href=\"productIndividualList.do?value=텐트/타프\">텐트/타프</a></li>\r\n");
      out.write("					<li><a class=\"nav-link scrollto\"\r\n");
      out.write("						href=\"productIndividualList.do?value=의자/테이블/퍼니처류\">의자/테이블/퍼니처류</a></li>\r\n");
      out.write("					<li><a class=\"nav-link scrollto\"\r\n");
      out.write("						href=\"productIndividualList.do?value=소품/액세서리\">소품/액세서리</a></li>\r\n");
      out.write("					<li><a class=\"nav-link scrollto\"\r\n");
      out.write("						href=\"productIndividualList.do?value=코펠/쿨러/식기류\">코펠/쿨러/식기류</a></li>\r\n");
      out.write("					<li><a class=\"nav-link scrollto\" href=\"campingRecommend.do\">캠핑장 찾기</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function delivery() {\r\n");
      out.write("			let singIn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			if (singIn == \"\") {\r\n");
      out.write("				alert(\"주문배송 페이지는 로그인 후 사용하실 수 있습니다.\")\r\n");
      out.write("				location.href = 'memberLoginForm.do';\r\n");
      out.write("			} else {\r\n");
      out.write("				location.href = 'deliveryResearch.do';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function myPage() {\r\n");
      out.write("			let singIn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			if (singIn == \"\") {\r\n");
      out.write("				alert(\"마이페이지는 로그인 후 사용하실 수 있습니다.\")\r\n");
      out.write("				location.href = 'memberLoginForm.do';\r\n");
      out.write("			} else {\r\n");
      out.write("				location.href = 'myPage.do';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("    \r\n");
      out.write("		function cart(){\r\n");
      out.write("			let singIn = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("			if (singIn == \"\") {\r\n");
      out.write("				alert(\"장바구니는 로그인 후 사용하실 수 있습니다.\")\r\n");
      out.write("				location.href = 'memberLoginForm.do';\r\n");
      out.write("			} else {\r\n");
      out.write("				location.href = 'cart.do';\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function googleTranslateElementInit() {\r\n");
      out.write("			new google.translate.TranslateElement({\r\n");
      out.write("				pageLanguage: 'ko,en',\r\n");
      out.write("				includedLanguages: 'ko,zh-CN,zh-TW,ja,vi,th,tl,km,my,mn,ru,en,fr,ar',\r\n");
      out.write("				layout: google.translate.TranslateElement.InlineLayout.SIMPLE,\r\n");
      out.write("				autoDisplay: false\r\n");
      out.write("			}, 'google_translate_element');\r\n");
      out.write("		}\r\n");
      out.write("		/* 다크모드 스크립트 */\r\n");
      out.write("		\r\n");
      out.write("		 document.addEventListener('DOMContentLoaded', function(){\r\n");
      out.write("           //다크모드 토글\r\n");
      out.write("           if(document.querySelector('.darkmode')){\r\n");
      out.write("               if(localStorage.getItem(\"darkmode\") == 'on'){\r\n");
      out.write("                   //다크모드 켜기\r\n");
      out.write("                   document.body.dataset.darkmode='on';\r\n");
      out.write("                   document.querySelector('#toggle-radio-dark').checked = true;\r\n");
      out.write("               }\r\n");
      out.write("               //다크모드 이벤트 핸들러\r\n");
      out.write("               document.querySelector('.darkmode').addEventListener(\"click\", e=>{\r\n");
      out.write("                   if(e.target.classList.contains('todark')){\r\n");
      out.write("                       document.body.dataset.darkmode='on';\r\n");
      out.write("                       localStorage.setItem(\"darkmode\", \"on\");\r\n");
      out.write("                   }else if(e.target.classList.contains('tolight')){\r\n");
      out.write("                       document.body.dataset.darkmode='off';\r\n");
      out.write("                       localStorage.setItem(\"darkmode\", \"off\");\r\n");
      out.write("                   }\r\n");
      out.write("               },false);\r\n");
      out.write("           }else{\r\n");
      out.write("               localStorage.removeItem(\"darkmode\");\r\n");
      out.write("           }\r\n");
      out.write("\r\n");
      out.write("       })\r\n");
      out.write("	</script>\r\n");
      out.write("	<script src=\"//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/layouts/header.jsp(37,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a class=\"small nav-link scrollto\"\r\n");
          out.write("							href=\"memberLoginForm.do\">로그인</a></li>\r\n");
          out.write("						<li><a class=\"small nav-link scrollto\" href=\"memberJoin.do\">회원가입</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/layouts/header.jsp(42,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty id }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a class=\"small nav-link scrollto\" href=\"memberLogout.do\">로그아웃</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/layouts/header.jsp(45,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth == 'A' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li><a class=\"small nav-link scrollto\"\r\n");
          out.write("							href=\"productInsertForm.do\">상품등록</a></li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
