/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-22 08:42:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#frm {\r\n");
      out.write("	margin: 70px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#frm h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.create {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	border-bottom: 1px solid #8aa1a1;\r\n");
      out.write("	margin: 50px auto 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	border-top: 3px solid #8aa1a1;\r\n");
      out.write("	margin-right: auto;\r\n");
      out.write("	margin-left: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	border-bottom: 1px dotted black;\r\n");
      out.write("	height: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col1 {\r\n");
      out.write("	background-color: #e8e8e8;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 0.8em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col2 {\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".addr {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but1 {\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: #8aa1a1;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but2 {\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	background-color: #8aa1a1;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: 2px solid #8aa1a1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but3 {\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	background-color: #8aa1a1;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: 2px solid #8aa1a1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but1:hover {\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	border: 2px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but2:hover {\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	border: 2px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".but3:hover {\r\n");
      out.write("	background-color: black;\r\n");
      out.write("	border: 2px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-size: 0.7em;\r\n");
      out.write("	margin: 5px 0 3px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a {\r\n");
      out.write("	font-size: 0.7em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".num {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-size: 0.7em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sample6_address{\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form id=\"frm\" action=\"memberInsert.do\" onsubmit=\"return formCheck()\"\r\n");
      out.write("		method=\"post\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"insert\">\r\n");
      out.write("				<h2>회원가입</h2>\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"col1\">이름<span class=\"num\"> *</span></td>\r\n");
      out.write("						<td class=\"col2\"><input type=\"text\" id=\"memberName\"\r\n");
      out.write("							name=\"memberName\" maxlength=\"10\" required=\"required\"\r\n");
      out.write("							placeholder=\"이름\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"col1\">아이디<span class=\"num\"> *</span></td>\r\n");
      out.write("						<td class=\"col2\"><input type=\"email\" id=\"memberId\"\r\n");
      out.write("							name=\"memberId\" maxlength=\"30\" required=\"required\"\r\n");
      out.write("							placeholder=\"e-mail 형식\">\r\n");
      out.write("							<button class='but1' type=\"button\" id=\"checkId\" value=\"No\"\r\n");
      out.write("								onclick=\"idCheck()\">중복확인</button></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"col1\">비밀번호<span class=\"num\"> *</span></td>\r\n");
      out.write("						<td class=\"col2\"><input type=\"password\" id=\"memberPw\"\r\n");
      out.write("							name=\"memberPw\" required=\"required\" maxlength=\"16\"\r\n");
      out.write("							placeholder=\"비밀번호\">\r\n");
      out.write("							<p>\r\n");
      out.write("								※비밀번호는 <span class=\"num\">문자, 숫자, 특수문자의 조합 10 ~ 16자리</span>로 입력이\r\n");
      out.write("								가능합니다.\r\n");
      out.write("							</p></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"col1\">비밀번호 확인<span class=\"num\"> *</span></td>\r\n");
      out.write("						<td class=\"col2\"><input type=\"password\" id=\"pwCheck\"\r\n");
      out.write("							name=\"pwCheck\" required=\"required\" maxlength=\"16\"\r\n");
      out.write("							placeholder=\"비밀번호 확인\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"col1\">전화번호<span class=\"num\"> *</span></td>\r\n");
      out.write("						<td class=\"col2\"><input type=\"tel\" id=\"memberTel\"\r\n");
      out.write("							name=\"memberTel\" required=\"required\" maxlength=\"13\"\r\n");
      out.write("							placeholder=\"전화번호\" />\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"col1\">주소<span class=\"num\"> *</span></td>\r\n");
      out.write("						<td class=\"col2\"><input type=\"text\" id=\"sample6_postcode\"\r\n");
      out.write("							placeholder=\"우편번호\"> <input type=\"button\"\r\n");
      out.write("							onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("							<input type=\"text\" id=\"sample6_address\" name=\"sample6_address\"\r\n");
      out.write("							placeholder=\"주소\" size=\"80\"> <input type=\"hidden\"\r\n");
      out.write("							id=\"sample6_extraAddress\" name=\"sample6_extraAddress\"\r\n");
      out.write("							placeholder=\"주소\" size=\"80\"> <br> <input type=\"text\"\r\n");
      out.write("							id=\"sample6_detailAddress\" name=\"sample6_detailAddress\"\r\n");
      out.write("							placeholder=\"상세주소\" size=\"80\"> <input type=\"hidden\" id=\"memberAddr\"\r\n");
      out.write("							name=\"memberAddr\">\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"create\">\r\n");
      out.write("				<input class=\"but2\" type=\"reset\" value=\"가입취소\"\r\n");
      out.write("					onclick=\"location.href='main.do'\"> &nbsp;&nbsp; <input\r\n");
      out.write("					class=\"but3\" type=\"submit\" value=\"회원가입\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write(" 	function formCheck(){\r\n");
      out.write("		let frm = document.getElementById(\"frm\");\r\n");
      out.write("		let sizePw = frm.memberPw.value.toString().length;\r\n");
      out.write("		console.log(sizePw);\r\n");
      out.write("		document.getElementById(\"memberAddr\").value = document.getElementById(\"sample6_address\").value + \" \" +\r\n");
      out.write("	  	document.getElementById(\"sample6_detailAddress\").value;\r\n");
      out.write("		if(10<= sizePw && sizePw <= 16 ) {\r\n");
      out.write("			if(frm.memberPw.value != frm.pwCheck.value){\r\n");
      out.write("				alert(\"패스워드가 일치 하지 않습니다.\");\r\n");
      out.write("				frm.memberPw.value = \"\";\r\n");
      out.write("				frm.pwCheck.value = \"\";\r\n");
      out.write("				frm.memberPw.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if(frm.checkId.value != \"Yes\") {\r\n");
      out.write("				alert(\"아이디 중복체크를 수행하세요.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}	\r\n");
      out.write("		} else {\r\n");
      out.write("			alert(\"비밀 번호는 10 ~ 16자리로 입력이 가능합니다.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write(" 	function idCheck(){\r\n");
      out.write("		let id = document.getElementById(\"memberId\").value;\r\n");
      out.write("		let url = \"ajaxCheckId.do?id=\"+id;\r\n");
      out.write("		fetch(url)  //ajax 호출\r\n");
      out.write("			.then(response => response.text())\r\n");
      out.write("			.then(text => htmlProcess(text));\r\n");
      out.write("	} \r\n");
      out.write("	\r\n");
      out.write("  	function htmlProcess(data){\r\n");
      out.write("		if(data == 'Yes'){\r\n");
      out.write("			alert(document.getElementById(\"memberId\").value + \"\\n 사용가능한 아이디 입니다.\");\r\n");
      out.write("			document.getElementById(\"checkId\").value = 'Yes';\r\n");
      out.write("		}else {\r\n");
      out.write("			alert(document.getElementById(\"memberId\").value + \"\\n 이미사용하는 아이디 입니다.\");\r\n");
      out.write("			document.getElementById(\"memberId\").value =\"\";\r\n");
      out.write("			document.getElementById(\"memberId\").focus();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("  	function sample6_execDaumPostcode(){\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                var addr = ''; \r\n");
      out.write("                var extraAddr = ''; \r\n");
      out.write("\r\n");
      out.write("                if (data.userSelectedType === 'R') { \r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { \r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample6_address\").value = addr +  document.getElementById(\"sample6_extraAddress\").value;\r\n");
      out.write("                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("                document.getElementById(\"memberAddr\").value = addr;\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("  	\r\n");
      out.write("</script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
